// src/components/MusicTable.vue
<!-- eslint-disable vue/valid-v-slot -->
<template>
  <v-card flat>
      <template v-slot:text>
          <v-text-field
              v-model="search"
              label="Search"
              prepend-inner-icon="mdi-magnify"
              variant="outlined"
              hide-details
              single-line
          ></v-text-field>
      </template>

      <v-data-table
          :headers="headers"
          :items="musicTracks"
          :search="search"
          :loading="loading"
      >
          <template #item.thumbnail="{ item }">
              <v-img
                  :src="item.thumbnail"
                  height="50"
                  width="50"
                  contain
              ></v-img>
          </template>
      </v-data-table>
  </v-card>
</template>

<script setup>
import { ref, onMounted } from "vue";

const search = ref("");
const loading = ref(true);
const musicTracks = ref([]);

const headers = [
  { key: "thumbnail", title: "Cover", sortable: false },
  { key: "title", title: "Title" },
  { key: "artist", title: "Artist" },
  { key: "album", title: "Album" },
  { key: "duration", title: "Duration" },
];

const fetchMusicData = async () => {
  try {
      const response = await fetch(
          "https://ujjwaljamuar.github.io/JSONsAPIs/All_Liked_Songs.json"
      );
      const data = await response.json();
      musicTracks.value = data.items;
  } catch (error) {
      console.error("Error fetching music data:", error);
  } finally {
      loading.value = false;
  }
};

onMounted(fetchMusicData);
</script>

// src/app/components/MusicTable/MusicTable.tsx
"use client"
import { useEffect, useState } from "react";
import Image from "next/image";
import "./MusicTable.css";

const MusicTable = () => {
    const [musicItems, setMusicItems] = useState([]);

    useEffect(() => {
        fetch("https://ujjwaljamuar.github.io/JSONsAPIs/All_Liked_Songs.json")
            .then((response) => response.json())
            .then((data) => setMusicItems(data["items"]))
            .catch((error) =>
                console.log(`Error fetching music API.\n ${error}`)
            );
    });

    return (
        <div
            className="maintable"
            style={{ border: "1px", borderColor: "black", height: "100%" }}
        >
            <table>
                <thead>
                    <tr>
                        <th>Cover</th>
                        <th>Title</th>
                        <th>Artist</th>
                        <th>Album</th>
                        <th>Duration</th>
                    </tr>
                </thead>
                <tbody>
                    {musicItems.map((item) => (
                        <tr key={item["videoId"]}>
                            <td
                                style={{
                                    height: "50px",
                                    width: "50px",
                                    objectFit: "contain",
                                }}
                            >
                                <Image src={item["thumbnail"]} alt="" />
                            </td>
                            <td>{item["title"]}</td>
                            <td>{item["artist"]}</td>
                            <td>{item["album"]}</td>
                            <td>{item["duration"]}</td>
                            <td>IN</td>
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
    );
};

export default MusicTable;
